name: Update Market Journal

on:
  schedule:
    - cron: "0 22 * * 1-5"   # Run Mon–Fri at 22:00 UTC (~5pm EST)
  workflow_dispatch:          # Allow manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch_prices.py
        run: python fetch_prices.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/etf_prices_log.csv
          git commit -m "Update market journal data"
          git push
