name: Update Market Journal

on:
  schedule:
    # 6:35pm EDT (Mar–Nov) = 22:35 UTC, Mon–Fri
    - cron: '35 22 * * 1-5'
    # 6:35pm EST (Nov–Mar) = 23:35 UTC, Mon–Fri
    - cron: '35 23 * * 1-5'
  workflow_dispatch:  # allow manual trigger

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python fetch_prices.py

      - name: Commit CSV update (if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/etf_prices_log.csv
            git commit -m "chore(data): update daily prices [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
